output_dir: ~/scratch/ncprior_output/
#checkpoint: /home/xinyu402/scratch/ncprior_output/ImageGeneration/MNIST/VAE_2022-12-04-19-51-31/model_epoch_30.pth

dataset:
  class: MNIST
  path: ~/scratch/image-datasets/

task:
  class: ImageGeneration
  model:
    class: VAE
    latent_dim: 16 # 128
    num_layer: 4 # 5
    hidden_dims: [128, 256, 512, 1024] # [32, 64, 128, 256, 512]
    kernel_size: 3
    stride: 2
    padding: 1
  kl_weight: 0.312

optimizer:
  class: Adam
  lr: 0.0005
  weight_decay: 1.e-5

#scheduler:
#  class: ExponentialLR
#  gamma: 0.95

engine:
  gpus: [0, ]
  batch_size: 64

train:
  num_epoch: 8
  #batch_per_epoch: 10

test_batch_size: 64
